-- DDL

-- 1
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YB CHAR(1) DEFAULT 'Y'    
);

-- 2
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

-- 3
ALTER TABLE TB_CATEGORY ADD PRIMARY KEY(NAME);

-- 4
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

-- 5
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10)
                                     MODIFY NAME VARCHAR(20);
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR(20);

-- 6
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;
ALTER TABLE TB_CATEGORY RENAME COLUMN CATEGORY TO CATEGORY_NAME;

-- 7
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN CLASS_TYPE_NO TO PK_CLASS_TYPE_NO;
ALTER TABLE TB_CATEGORY RENAME COLUMN CATEGORY_NAME TO PK_CATEGORY_NAME;

-- 8
INSERT INTO TB_CATEGORY VALUES ('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회', 'Y');
COMMIT;


 --FOREIGN KEY : ALTER TABLE 테이블명 ADD [CONSTRAINT 제약조건명] FOREIGN KEY (컬럼명) REFERENCES 참조할 테이블명 (컬럼명);
-- 9
ALTER TABLE TB_DEPARTMENT 
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY
FOREIGN KEY(CATEGORY) REFERENCES
TB_CATEGORY(PK_CATEGORY_NAME);

-- 10
CREATE VIEW VW_학생일반정보
AS (SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 학생이름, STUDENT_ADDRESS AS 주소
    FROM TB_STUDENT
    );

-- 11
CREATE VIEW VW_지도면담
AS SELECT 
S.STUDENT_NAME AS 학생이름, 
D.DEPARTMENT_NAME AS 학과이름,
P.PROFESSOR_NAME AS 지도교수이름
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR P ON(S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
ORDER BY DEPARTMENT_NAME;

-- 12
CREATE VIEW VW_학과별학생수
AS (SELECT
DEPARTMENT_NAME,
COUNT(*) AS STUDENT_COUNT
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
GROUP BY DEPARTMENT_NAME
);

-- 13
UPDATE VW_학생일반정보
SET 학생이름 = '박준언'
WHERE 학번 = 'A213046';
-- 14
CREATE OR REPLACE VIEW VW_학생일반정보
AS (SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 학생이름, STUDENT_ADDRESS AS 주소
    FROM TB_STUDENT
    )
WITH READ ONLY;

-- 15
SELECT CLASS_NO AS 과목번호, CLASS_NAME AS 과목이름, COUNT(*) AS "누적수강생수(명)"
