-- Additional SELECT - Option

-- 1
SELECT STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

-- 2
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

-- 3
SELECT STUDENT_NAME AS 학생이름, STUDENT_NO AS 학번, STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,2) IN ('99', '98', '97', '96', '95', '94', '93', '92', '91', '90')
            AND SUBSTR(STUDENT_ADDRESS,1,3) IN ('강원도', '경기도')
ORDER BY STUDENT_NAME;
            
-- 4
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN;

-- 5
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = '200402'
            AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO;

-- 6
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NO;

-- 7
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

-- 8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING(DEPARTMENT_NO);

-- 9
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

-- 10
SELECT STUDENT_NO AS 학번, STUDENT_NAME AS "학생 이름", ROUND(AVG(POINT),1) AS "전체 평점"
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME;

-- 11
SELECT 
D.DEPARTMENT_NAME AS 학과이름,
S.STUDENT_NAME AS 학생이름,
P.PROFESSOR_NAME AS 지도교수이름
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
JOIN TB_PROFESSOR P ON S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
WHERE S.STUDENT_NO = 'A313047';

-- 12
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_CLASS USING (DEPARTMENT_NO)
WHERE SUBSTR(TERM_NO,1,4) = '2007'
            AND CLASS_NAME = '인간관계론'
GROUP BY STUDENT_NAME, TERM_NO;

-- 13
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_PROFESSOR P
JOIN TB_DEPARTMENT D ON (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_CLASS C ON(P.DEPARTMENT_NO = C.DEPARTMENT_NO)
WHERE PREATTENDING_CLASS_NO IS NULL
            AND CATEGORY = '예체능'
GROUP BY CLASS_NAME, DEPARTMENT_NAME;

-- 14
SELECT STUDENT_NAME AS 학생이름,
NVL(PROFESSOR_NAME, '지도교수 미지정') AS 지도교수
FROM TB_STUDENT S
JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
WHERE S.DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                                        FROM TB_DEPARTMENT 
                                        WHERE DEPARTMENT_NAME = '서반아어학과')
ORDER BY S.STUDENT_NO;

-- 15
SELECT STUDENT_NO AS 학번, 
STUDENT_NAME AS 이름, 
DEPARTMENT_NAME AS "학과 이름",
AVG(POINT) AS 평점
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N' 
GROUP BY STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
HAVING AVG(POINT) > 4.0;

-- 16
SELECT CLASS_NO, CLASS_NAME, AVG(POINT)
FROM TB_CLASS
JOIN TB_GRADE USING (CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
GROUP BY CLASS_NO, CLASS_NAME;

-- 17
SELECT A.STUDENT_NAME, A.STUDENT_ADDRESS
FROM TB_STUDENT A
JOIN TB_STUDENT B ON (A.STUDENT_ADDRESS = B.STUDENT_ADDRESS)
WHERE A.DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                                        FROM TB_STUDENT
                                        WHERE STUDENT_NAME = '최경희');
                                        
-- 18 ???
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE AVG(POINT) = 
        (SELECT MAX(AVG(POINT))
            FROM TB_STUDENT);
            
-- 19
SELECT DEPARTMENT_NAME AS "계열 학과명", ROUND(AVG(POINT),1) AS 전공평점
FROM TB_DEPARTMENT
JOIN TB_CLASS USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (CLASS_NO)
WHERE CATEGORY = (SELECT CATEGORY
                            FROM TB_DEPARTMENT
                            WHERE DEPARTMENT_NAME = '환경조경학과')
GROUP BY DEPARTMENT_NAME;