--Additional SELECT

-- 1
SELECT STUDENT_NO AS 학번, 
STUDENT_NAME AS 이름,
TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') AS 입학년도
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '영어영문학과'
ORDER BY 입학년도;

-- 2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE ('___');

-- 3
SELECT PROFESSOR_NAME AS 교수이름, 
FLOOR(MONTHS_BETWEEN(SYSDATE,TO_DATE(SUBSTR(PROFESSOR_SSN,1,6),'RRMMDD'))/ 12) AS 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1
ORDER BY 나이;

SELECT PROFESSOR_NAME 교수이름, 
EXTRACT(YEAR FROM SYSDATE) - (19 || SUBSTR(PROFESSOR_SSN, 1, 2)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 나이;


-- 4
SELECT SUBSTR(PROFESSOR_NAME, 2) AS 이름
FROM TB_PROFESSOR;

-- 5
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE FLOOR(MONTHS_BETWEEN(SYSDATE,TO_DATE(SUBSTR,1,6),'RRMMDD'))/ 12) > 20;

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6))) > 19;


-- 6
SELECT TO_CHAR(TO_DATE('20201224'), 'DAY')  AS 요일 
FROM DUAL;

-- 7
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'),'YYYY'),
TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'),'YYYY'),
TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'YYYY'), 
TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'YYYY')
FROM DUAL;

-- 8
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE ('A%');

-- 9
SELECT ROUND(AVG(POINT), 1)AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10
SELECT DEPARTMENT_NO AS 학과번호, COUNT(*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 학과번호;

-- 11
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12
SELECT SUBSTR(TERM_NO,1,4) AS 년도, AVG(POINT) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY TERM_NO;

-- 13
SELECT DEPARTMENT_NO AS 학과코드명, COUNT(ABSENCE_YN) AS "휴학생 수"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 14
SELECT STUDENT_NAME AS 동일이름, COUNT(*) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1;

-- 15
SELECT SUBSTR(TERM_NO,1,4) AS 년도, SUBSTR(TERM_NO,5) AS 학기, ROUND(AVG(POINT), 1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY TERM_NO;