INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (1, '공지사항');


INSERT INTO BOARD (
    BOARD_NO,
    BOARD_TYPE,
    CATEGORY_NO,
    BOARD_TITLE,
    BOARD_CONTENT,
    BOARD_WRITER,
    COUNT,
    CREATE_DATE,
    STATUS
) VALUES (
    1,
    1,
    1,  -- 존재하는 카테고리 번호로 수정
    '게시글 제목입니다1.',
    '게시글 내용입니다1.',
    2, -- 존재하는 회원 번호로 수정
    0,
    SYSDATE,
    'Y'
);

COMMIT;
UPDATE BOARD
		   SET BOARD_TYPE = 10
		 WHERE BOARD_TYPE = 1;
         
SELECT * FROM BOARD;

SELECT BOARD_NO,
				CATEGORY_NAME,
				BOARD_TITLE,
				MEMBER_ID,
				COUNT,
				TO_CHAR(CREATE_DATE, 'YYYY-MM-DD') AS "CREATE_DATE"
		FROM BOARD B
		LEFT JOIN CATEGORY USING(CATEGORY_NO)
		LEFT JOIN MEMBER M ON(BOARD_WRITER = MEMBER_NO)
		WHERE B.STATUS = 'Y'
		ORDER BY BOARD_NO DESC;
        
SELECT BOARD_NO, BOARD_TYPE, STATUS FROM BOARD;

UPDATE BOARD
SET BOARD_TYPE = 1
WHERE BOARD_TYPE IN (2, 10);

commit;

DELETE FROM BOARD
WHERE BOARD_NO IN (1, 2, 3);