DROP TABLE SALARY;
DROP TABLE EMPLOYEE;
DROP TABLE DEPT_TABLE;

CREATE TABLE DEPT_TABLE(
    DEPT_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    DEPT_TITLE VARCHAR2(20) NOT NULL
);

CREATE TABLE EMPLOYEE(
    EMP_NO NUMBER PRIMARY KEY,
    DEPT_CODE VARCHAR(20) NOT NULL ,
    EMP_NAME VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    HIRE_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (DEPT_CODE) REFERENCES DEPT_TABLE(DEPT_ID)
);
    
CREATE TABLE SALARY(
    EMP_NO NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(20) NOT NULL,
    DEPT_CODE VARCHAR(20) NOT NULL,
    SALARY NUMBER NOT NULL,
    FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEE(EMP_NO)
);

INSERT ALL 
    INTO DEPT_TABLE VALUES('D1', '인사관리부')
    INTO DEPT_TABLE VALUES('D2', '마케킹부')
    INTO DEPT_TABLE VALUES('D3', '해외영업부1')
    INTO DEPT_TABLE VALUES('D4', '해외영업부2')
    INTO DEPT_TABLE VALUES('D5', '해외영업부3')
    INTO DEPT_TABLE VALUES('D6', '전력기획부')
    SELECT * FROM DUAL;
    

ALTER TABLE EMPLOYEE MODIFY DEPT_CODE VARCHAR(20);


INSERT INTO EMPLOYEE 
	VALUES(
	200,
	 'D1',
	 '박준언',
	 '인천',
	 'qwe',
	 '101',
	 SYSDATE
    );
    commit;
DELETE FROM EMPLOYEE
WHERE EMP_NO = EMP_NO;